Allow users to specify a custom output length when resampling
adefossez/julius pull request #14
Opened 2021-07-26 08:13 UTC by iver56

Close #13

2021-07-26 13:52 UTC, adefossez requested changes
Thanks a lot for the PR. After thinking more on this I think things are more complex than just choosing between `floor` and `ceil`. For instance, let say I do the following

```python
x = torch.randn(19)
y = julius.resample_frac(x, 7, 1)  # y.shape is [2]
x2 = julius.resample_frac(y, 1, 7). # x2 shape is [14]
```
Now I want to have a way to make `x2` of the same size as `x`. With the current diff, this is not possible. I can pick `y` to be of length `3`, but I cannot take x2 of length 19 (only 21, or 22).

In fact, given an input of length L, we know that the true input length (given as a float, for instance if it is itself the output of a previous resampliong) is between `(L-1, L]` (for instance the ideal length of y would be 2.71), so that the true output length as a float could be anywhere between `((L-1) * new / old, L * new / old]`, and the possible actual output lengths could be anything in `(floor((L-1) * new) / old, ceil(L * new / old)]` (i would say the left side of the segment is excluded, because it would actually be the same as the right side for an input that is smaller).

nit: if you have time, I would also add a `full` boolean parameter that automatically pick the longest possible output without having the user doing the computation. After doing arbitrary sequences of resampling, it is always possible to just keep the first L steps, rather than computing all the intermediate sizes that will make it work. If you do that, we could actually chose to be more permissive in the previous definition of the available segment, for instance to do something like:

```python
x = torch.randn(19)
y = julius.resample_frac(x, 7, 1, full=True) #  length is 3
z = julius.resample_frac(x, 5, 1, full=True) # length is 1
y2 = julius.resample_frac(x, 1, 5)  # length is 5
x2 = julius.resample_frac(x, 1, 7, length=len(x))  # normally 19 shouldn't be acceptable here
```

In that case the segment would be [0, ceil(L * new / old)], which would be convenient but maybe a bit too permissive. What do you think?

2021-07-26 13:52 UTC, adefossez commented on julius/resample.py
> +from typing import Optional
nit: imports from standard library goes together in the paragraph above.

2021-07-26 13:52 UTC, adefossez commented on tests/test_lowpass.py
> +TOLERANCE = 1  # Tolerance to errors as percentage of the std of the input signal
thanks for the fix

2021-07-26 14:16 UTC, iver56 commented
Good point. I'll make the range check more permissive. But should output_length=0 really be allowed? That seems counter-intuitive.

I prefer to leave the `full` parameter for future work

2021-07-27 17:04 UTC, adefossez commented
thanks for the update!

2021-07-27 17:04 UTC, merged

2021-07-27 17:05 UTC, adefossez commented
I'll push a new version of julius to PyPI tomorrow.

2021-07-27 19:34 UTC, iver56 commented
Sweet, thanks for the swift response!

2021-07-28 09:20 UTC, adefossez commented
I made some minor edits https://github.com/adefossez/julius/commit/3804ada9ecd61d1566dfd786714cfc2ec55eb3f4 and I added the `full` parameter.
The new version has been released to PyPI as 0.2.5.